version: "3.9"

services:
  app1:
    build: ./app1
    container_name: app1
    ports:
      - "5001:5000"

  app2:
    build: ./app2
    container_name: app2
    depends_on:
     - app1 
    ports:
      - "5002:5000"

  aggregator:
    build: ./aggregator
    container_name: aggregator
    depends_on:
     - app2
    restart: always

