name: Docker Networking CI/CD

# Trigger on push or pull request to main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Docker Buildx (for building multi-platform images if needed)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Build Docker Compose services
      - name: Build Docker Compose services
        working-directory: ./docker-networking-demo
        run: docker compose build

      # 4. Run containers in detached mode
      - name: Run Docker Compose services
        working-directory: ./docker-networking-demo
        run: docker compose up -d

      # 5. Wait a few seconds for containers to start
      - name: Wait for services
        run: sleep 10

      # 6. Test if aggregator is producing logs
      - name: Test aggregator output
        working-directory: ./docker-networking-demo
        run: |
          echo "Checking aggregator logs..."
          AGG_LOG=$(docker logs docker-networking-demo-aggregator-1 2>/dev/null | tail -n 10 || true)
          if [ -z "$AGG_LOG" ]; then
            echo "Aggregator log is empty. CI failed."
            exit 1
          else
            echo "Aggregator is running and producing logs:"
            echo "$AGG_LOG"
          fi

      # 7. Stop and remove containers
      - name: Tear down Docker Compose
        working-directory: ./docker-networking-demo
        run: docker compose down
