name: Docker Nerworking CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@4

      - name: set up docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Compose Services
        run: docker compose build

      - name: Run docker compose services
        run: docker compose up -d

      - name: Wait for aggregator to start
        run: sleep 10  # gives containers a few seconds to start and write logs

      - name: Test aggregator output
        run: |
          AGG_LOG=$(docker logs docker-networking-demo-aggregator-1 | tail -n 10)
          if [[ -z "$AGG_LOG" ]]; then
            echo "Aggregator log is empty. CI failed."
            exit 1
          else
            echo "Aggregator is running and producing logs:"
            echo "$AGG_LOG"
          fi

      - name: Stop and remove containers
        run: docker compose down
